# Generated by Django 5.2.8 on 2025-11-09 20:20

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('tipo_usuario', models.CharField(choices=[('independiente', 'Independiente'), ('mantenido', 'Mantenido')], default='independiente', max_length=20)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.PositiveSmallIntegerField()),
                ('anio', models.PositiveSmallIntegerField(default=2025)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reportes', to='Ahorro_Peak_App.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frecuencia', models.CharField(choices=[('diaria', 'Diaria'), ('semanal', 'Semanal'), ('mensual', 'Mensual'), ('entrar', 'Cada vez que se ingrese a la pagina o inicie sesion')], default='entrar', max_length=20)),
                ('contenido', models.TextField()),
                ('estado', models.CharField(choices=[('activa', 'Activa'), ('inactiva', 'Inactiva')], default='activa', max_length=10)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='Ahorro_Peak_App.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='MetaAhorro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_meta', models.CharField(max_length=100)),
                ('monto_objetivo', models.PositiveIntegerField()),
                ('fecha_limite', models.DateTimeField()),
                ('progreso_actual', models.PositiveIntegerField(default=0)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metas', to='Ahorro_Peak_App.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Ingreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_ingreso', models.CharField(choices=[('sueldo', 'Sueldo'), ('bono', 'Bono'), ('regalo', 'Regalo'), ('personalizado', 'Personalizado')], default='sueldo', max_length=20)),
                ('descripcion', models.CharField(blank=True, max_length=100, null=True)),
                ('monto', models.PositiveIntegerField()),
                ('fecha_ingreso', models.DateTimeField(default=django.utils.timezone.now)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingresos', to='Ahorro_Peak_App.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Gastos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_gasto', models.CharField(choices=[('luz', 'Luz'), ('agua', 'Agua'), ('gas', 'Gas'), ('mercaderia', 'Mercaderia'), ('internet', 'Internet'), ('entretenimiento', 'Entretenimiento'), ('personalizado', 'Personalizado')], default='personalizado', max_length=20)),
                ('descripcion', models.CharField(blank=True, max_length=100, null=True)),
                ('monto', models.PositiveIntegerField()),
                ('fecha_gasto', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gastos', to='Ahorro_Peak_App.usuario')),
            ],
        ),
    ]
